receivers:
  otlp:
    protocols:
      http:
        cors:
          allowed_origins:
            - "http://localhost:5174"
        endpoint: "0.0.0.0:55681"
      grpc:

exporters:
  debug:
  otlp:
    endpoint: "tempo:4317"
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [debug, otlp]
